endpoint: wss://hydradx-rpc.dwellir.com
mock-signature-host: true
block: ${env.HYDRATION_BLOCK_NUMBER}
db: ./db.sqlite

import-storage:
  System:
    Account:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY # Alice
        - providers: 1
          data:
            free: '10000000000000000000'

runtime-log-level: 5
