endpoint: wss://westend-collectives-rpc.polkadot.io
mock-signature-host: true
block: ${env.ROCOCO_BRIDGE_HUB_BLOCK_NUMBER}
db: ./db.sqlite

import-storage:
  System:
    Account:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - providers: 1
          data:
            free: 1000000000000000

runtime-log-level: 5
wasm-override: wasms/bridge_hub_rococo_runtime.compact.compressed.wasm
